/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TimelineRouteImport } from './routes/timeline'
import { Route as QuizRouteImport } from './routes/quiz'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ExhibitsIndexRouteImport } from './routes/exhibits.index'
import { Route as ExhibitsSlugRouteImport } from './routes/exhibits.$slug'

const TimelineRoute = TimelineRouteImport.update({
  id: '/timeline',
  path: '/timeline',
  getParentRoute: () => rootRouteImport,
} as any)
const QuizRoute = QuizRouteImport.update({
  id: '/quiz',
  path: '/quiz',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ExhibitsIndexRoute = ExhibitsIndexRouteImport.update({
  id: '/exhibits/',
  path: '/exhibits/',
  getParentRoute: () => rootRouteImport,
} as any)
const ExhibitsSlugRoute = ExhibitsSlugRouteImport.update({
  id: '/exhibits/$slug',
  path: '/exhibits/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/quiz': typeof QuizRoute
  '/timeline': typeof TimelineRoute
  '/exhibits/$slug': typeof ExhibitsSlugRoute
  '/exhibits/': typeof ExhibitsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/quiz': typeof QuizRoute
  '/timeline': typeof TimelineRoute
  '/exhibits/$slug': typeof ExhibitsSlugRoute
  '/exhibits': typeof ExhibitsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/quiz': typeof QuizRoute
  '/timeline': typeof TimelineRoute
  '/exhibits/$slug': typeof ExhibitsSlugRoute
  '/exhibits/': typeof ExhibitsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/contact'
    | '/quiz'
    | '/timeline'
    | '/exhibits/$slug'
    | '/exhibits/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/contact'
    | '/quiz'
    | '/timeline'
    | '/exhibits/$slug'
    | '/exhibits'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/contact'
    | '/quiz'
    | '/timeline'
    | '/exhibits/$slug'
    | '/exhibits/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ContactRoute: typeof ContactRoute
  QuizRoute: typeof QuizRoute
  TimelineRoute: typeof TimelineRoute
  ExhibitsSlugRoute: typeof ExhibitsSlugRoute
  ExhibitsIndexRoute: typeof ExhibitsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/timeline': {
      id: '/timeline'
      path: '/timeline'
      fullPath: '/timeline'
      preLoaderRoute: typeof TimelineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quiz': {
      id: '/quiz'
      path: '/quiz'
      fullPath: '/quiz'
      preLoaderRoute: typeof QuizRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/exhibits/': {
      id: '/exhibits/'
      path: '/exhibits'
      fullPath: '/exhibits/'
      preLoaderRoute: typeof ExhibitsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/exhibits/$slug': {
      id: '/exhibits/$slug'
      path: '/exhibits/$slug'
      fullPath: '/exhibits/$slug'
      preLoaderRoute: typeof ExhibitsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ContactRoute: ContactRoute,
  QuizRoute: QuizRoute,
  TimelineRoute: TimelineRoute,
  ExhibitsSlugRoute: ExhibitsSlugRoute,
  ExhibitsIndexRoute: ExhibitsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
